<?php declare(strict_types=1);
include 'header.tpl.php'; ?>
<p>This developer documentation consists of multiple key aspects that are relevant for developers. All pages are automatically generated by the provided source code, unit tests, code coverage inspection as well as manually generated markdown documentation.</p>
<h1>Guide</h1>
<p>The developer guides intention is to provide useful information to help you to understand the structure of the application, important classes, workflows and standards for code quality as well as code style. The intention is to provide enough information to get a basic understanding of these key elements for module developers, frontend developers or developers working on the core application.</p>

<p>The guide is not explaining in detail how to use classes, for this you can find the automatically generated code documentation. All the provided information are very important to ensure the quality of the published code and often are mandatory. Not following these guides can cause security issues, worsen the user experience or even cause malfunction as well as make it difficult for other developers to understand the code.</p>
<h1>Docs</h1>
<p>The automatic generated documentation is intending to provide a php.net like entry point to classes and methods. The documentation is created by parsing the classes, methods and their DocComments. The more in depth the code documentation in the source code the better the automatic generated documentation will be. Not only are the basic DocBlock comments supported but also some additional comments for extended documentation.</p>

<p>Apart from basic code documentation the code coverage report for these classes and methods will be used and visualized in order to provide a better feeling for potential improvements.</p>
<h1>Test</h1>
<p>The test page analyses the test results and provides an overview of errors, failures, warnings, etc. of tests. These information can be used in order to fix existing problems. Additional general information with regards to execution time, amount of test suits as well as asserts are provided as well.</p>
<h1>Coverage</h1>
<p>While the basic code coverage is already included into the class and method documentation this page provides an overview about general statistics as well as a list of potential classes and methods to improve. For a full code coverage view please make use of the in built html generation for code coverage of the unit testing library.</p>
<?php include 'footer.tpl.php'; ?>